In [1]:
print("ah yes implementation")

ah yes implementation


# Image Opening

In [2]:
from PIL import Image
import numpy as np

In [3]:
%timeit img=Image.open("lena_gray.gif") 


The slowest run took 247.18 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 5: 57.9 µs per loop


In [4]:
img=Image.open("lena_gray.gif") 

Numpy array

In [5]:
nparr=np.array(img)
nparr

array([[116, 116, 116, ..., 112,  11, 133],
       [116, 116, 116, ..., 112,  11, 133],
       [116, 116, 116, ..., 112,  11, 133],
       ...,
       [ 77,  77, 177, ..., 145, 147, 148],
       [183, 183,  65, ..., 145,  36, 143],
       [183, 183,  65, ..., 145,  36, 143]], dtype=uint8)

In [6]:
nparr.shape

(512, 512)

In [7]:
nparr.strides

(512, 1)

In [8]:
nparr.itemsize

1

# Image Blocks
For now only for gray scale

In [9]:
# https://stackoverflow.com/questions/13682604/slicing-a-numpy-image-array-into-blocks/19163700

In [10]:

# """Very basic multi dimensional rolling window. window should be the shape of
#     of the desired subarrays. Window is either a scalar or a tuple of same size
#     as `arr.shape`.
#     """
# window=(128,128)
# shape = np.array(nparr.shape*2)
# strides = np.array(nparr.strides*2)
# window = np.asarray(window)
# shape[nparr.ndim:] = window # new dimensions size
# shape[:nparr.ndim] -= window - 1
# if np.any(shape < 1):
#   raise ValueError('window size is too large')


In [11]:
# %timeit np.lib.stride_tricks.as_strided(nparr, shape=shape, strides=strides)

In [12]:
# slices=np.lib.stride_tricks.as_strided(nparr, shape=shape, strides=strides)

# slices

In [13]:
# slices.shape

In [14]:
# %timeit slices = slices.reshape(-1,slices.shape[2:])

In [15]:
# slices = slices.reshape(-1,slices.shape[2:])

In [16]:
# from sklearn.feature_extraction import image

In [17]:
# %timeit image.extract_patches_2d(nparr, (2, 2))

In [18]:
# #My method
# window=(int(512/4),int(512/4))#128x128
# slices=np.ndarray(shape=(4, 4))#(4,4)
# slices.shape

In [19]:
#  window

In [20]:
# for r in range(0,nparr.shape[0]-window[0], window[0]):
#   for c in range(0,nparr.shape[1]-window[1],window[1]):
#     slices[int(r/window[0]), int(c/window[1])]=nparr[r:r+window[0],c:c+window[1]]

In [21]:
# slices

4x4 blocks

In [22]:
%timeit nparr.reshape((4,4,128,128))

The slowest run took 33.21 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 5: 414 ns per loop


In [23]:
blocks16=nparr.reshape((4,4,128,128))
blocks16

array([[[[116, 116, 116, ...,  25, 131,  23],
         [131,  24,  21, ...,  24,  22, 128],
         [128, 126, 130, ..., 120, 121, 121],
         ...,
         [ 27,  23, 135, ..., 131, 133, 132],
         [131, 131,  25, ...,  11,  11,  10],
         [  9, 118, 120, ..., 173, 171,  69]],

        [[ 10,  10,  10, ..., 134, 135, 135],
         [134, 134, 134, ..., 134, 134,  22],
         [ 22,  21, 132, ..., 119,  10, 118],
         ...,
         [135,  25, 137, ..., 105, 109, 104],
         [209, 101,  99, ..., 125,  18,  18],
         [127, 127, 125, ..., 168, 169, 175]],

        [[114, 114, 113, ...,  27, 139,  28],
         [ 26, 136,  28, ..., 101, 103, 207],
         [204, 101, 211, ...,  16, 124,  19],
         ...,
         [ 29,  30, 140, ...,  96, 205, 100],
         [ 96,  92, 196, ..., 146,  30,  28],
         [ 25, 129,  20, ...,   7,   7,   7]],

        [[ 35,  35, 146, ...,  30,  29,  28],
         [ 29, 136,  28, ..., 202, 203,  97],
         [ 97, 198, 194, ..., 14

Lookup Table

In [31]:
lookup=np.array([[(0,0),(1,3),(3,1),(2,2)],   [(0,1),(1,2),(3,0),(2,3)],  [(1,0),(0,2),(2,1),(3,3)],   [(1,1),(0,3),(2,0),(3,2)]])
lookup

array([[[0, 0],
        [1, 3],
        [3, 1],
        [2, 2]],

       [[0, 1],
        [1, 2],
        [3, 0],
        [2, 3]],

       [[1, 0],
        [0, 2],
        [2, 1],
        [3, 3]],

       [[1, 1],
        [0, 3],
        [2, 0],
        [3, 2]]])

4x4 then 16x16

In [35]:
singleblock=blocks16[0,0]
singleblock.shape

(128, 128)

In [36]:
singleblock.reshape((16,16,4,4))

ValueError: ignored

In [33]:
%timeit nparr.reshape((4,4,128,128,16,16))

ValueError: ignored

In [38]:
blocks4x16=nparr.reshape((4,4,16,16,8,8))
blocks4x16

array([[[[[[116, 116, 116, ...,  10,   7,   8],
           [114, 116, 116, ...,   7, 117,  11],
           [ 10, 119,   8, ..., 119, 120,  10],
           ...,
           [114,   6, 114, ...,   1,   2, 112],
           [111, 111,   5, ...,   5, 116,   8],
           [ 15, 123,  12, ...,  29, 138, 144]],

          [[ 40,  40, 150, ...,  40,  37, 149],
           [145,  38,  36, ...,  36, 145, 142],
           [142, 143,  35, ...,  34,  34,  34],
           ...,
           [ 34,  33, 138, ..., 138,  28,  29],
           [141, 136,  28, ..., 136,  28, 135],
           [ 27, 132,  24, ...,  25, 131,  23]],

          [[131,  24,  21, ...,  23,  23,  25],
           [ 21,  20, 131, ...,  23, 133, 132],
           [130, 134,  24, ..., 132,  24,  23],
           ...,
           [131,  21, 131, ..., 131,  22,  22],
           [129,  22, 130, ...,  22,  23, 131],
           [ 22,  21,  20, ...,  23,  22,  23]],

          ...,

          [[145, 141, 139, ..., 131,  21,  19],
           [127,  

In [42]:
blocks4x16[0,0,0,0]

array([[116, 116, 116,   8, 116,  10,   7,   8],
       [114, 116, 116, 117,  11,   7, 117,  11],
       [ 10, 119,   8,   8, 120, 119, 120,  10],
       [ 12,  10, 120, 121, 119, 120, 120, 119],
       [120, 118,  11, 117, 118,   5, 117, 114],
       [114,   6, 114, 111,   3,   1,   2, 112],
       [111, 111,   5,   1, 113,   5, 116,   8],
       [ 15, 123,  12, 127, 132,  29, 138, 144]], dtype=uint8)

In [ ]:
finalblocks=nparr.reshape((4,4,16,16,4,4,2,2))
finalblocks

In [47]:
finalblocks[0,0,0,0,0]

array([[[116, 116],
        [116,   8]],

       [[116,  10],
        [  7,   8]],

       [[114, 116],
        [116, 117]],

       [[ 11,   7],
        [117,  11]]], dtype=uint8)