In [1]:
from PIL import Image
import numpy as np

In [2]:
def getblocks(image: np.ndarray, blockshape: tuple, moveAxis: bool = True) -> np.ndarray:
    '''
    takes the array of image in grey= 2D and in RGB = 3D
    takes the numpy array and converts it the the blocks in the fastest way
    '''
    if len(image.shape) == 2:
        mode = "grey"
        image = image.reshape(*image.shape, 1)
    else:
        mode = "color"

    img_height, img_width, channels = image.shape
    tile_height, tile_width = blockshape

    if img_height % tile_height != 0 or img_width % tile_width != 0:
        print("warning: Block size is not fit for the image!")

    tiled_array = image.reshape(
        img_height//tile_height, tile_height, img_width//tile_width, tile_width, channels)
    tiled_array = tiled_array.swapaxes(1, 2)

    if moveAxis:
        tiled_array = tiled_array.reshape(-1,
                                          *(tile_height, tile_width, channels))
        tiled_array = np.moveaxis(tiled_array, source=len(
            tiled_array.shape)-1, destination=1)

    return tiled_array


def combineBlocks(tiled_array: np.ndarray, imageshape: tuple, blockshape: tuple, movedAxis: bool = True) -> np.ndarray:

    if len(imageshape) == 2:
        mode = "grey"
        imageshape = *imageshape, 1
    else:
        mode = "color"

    img_height, img_width, channels = imageshape
    tile_height, tile_width = blockshape

    if movedAxis:
        image = tiled_array.copy()
        image = image.reshape(img_height//tile_height, tile_height,
                              img_width//tile_width, tile_width, channels)
        swapaxisShape = list(image.shape)
        swapaxisShape[1], swapaxisShape[2] = swapaxisShape[2], swapaxisShape[1]
        image = image.reshape(swapaxisShape)
        image = image.swapaxes(1, 2)
    else:
        image = tiled_array
        # IDK have completed this else case. Btw we aren't using this case lol :)

    return image.reshape(imageshape)


In [3]:
image = np.arange(1,(16*16)+1).reshape(16,16)
image

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16],
       [ 17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,
         30,  31,  32],
       [ 33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,  44,  45,
         46,  47,  48],
       [ 49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
         62,  63,  64],
       [ 65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
         78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,
         94,  95,  96],
       [ 97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109,
        110, 111, 112],
       [113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
        126, 127, 128],
       [129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141,
        142, 143, 144],
       [145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157,
        158, 159, 160],
       [161, 162, 163, 164, 16

In [5]:
hehe = getblocks(image, (4, 4))
hehe.shape, hehe.strides, hehe


((16, 1, 4, 4),
 (64, 4, 16, 4),
 array([[[[  1,   2,   3,   4],
          [ 17,  18,  19,  20],
          [ 33,  34,  35,  36],
          [ 49,  50,  51,  52]]],
 
 
        [[[  5,   6,   7,   8],
          [ 21,  22,  23,  24],
          [ 37,  38,  39,  40],
          [ 53,  54,  55,  56]]],
 
 
        [[[  9,  10,  11,  12],
          [ 25,  26,  27,  28],
          [ 41,  42,  43,  44],
          [ 57,  58,  59,  60]]],
 
 
        [[[ 13,  14,  15,  16],
          [ 29,  30,  31,  32],
          [ 45,  46,  47,  48],
          [ 61,  62,  63,  64]]],
 
 
        [[[ 65,  66,  67,  68],
          [ 81,  82,  83,  84],
          [ 97,  98,  99, 100],
          [113, 114, 115, 116]]],
 
 
        [[[ 69,  70,  71,  72],
          [ 85,  86,  87,  88],
          [101, 102, 103, 104],
          [117, 118, 119, 120]]],
 
 
        [[[ 73,  74,  75,  76],
          [ 89,  90,  91,  92],
          [105, 106, 107, 108],
          [121, 122, 123, 124]]],
 
 
        [[[ 77,  78,  79,  80

In [7]:
sixtenb=hehe.copy()
sixtenb.shape,sixtenb.strides, sixtenb

((16, 1, 4, 4),
 (64, 64, 16, 4),
 array([[[[  1,   2,   3,   4],
          [ 17,  18,  19,  20],
          [ 33,  34,  35,  36],
          [ 49,  50,  51,  52]]],
 
 
        [[[  5,   6,   7,   8],
          [ 21,  22,  23,  24],
          [ 37,  38,  39,  40],
          [ 53,  54,  55,  56]]],
 
 
        [[[  9,  10,  11,  12],
          [ 25,  26,  27,  28],
          [ 41,  42,  43,  44],
          [ 57,  58,  59,  60]]],
 
 
        [[[ 13,  14,  15,  16],
          [ 29,  30,  31,  32],
          [ 45,  46,  47,  48],
          [ 61,  62,  63,  64]]],
 
 
        [[[ 65,  66,  67,  68],
          [ 81,  82,  83,  84],
          [ 97,  98,  99, 100],
          [113, 114, 115, 116]]],
 
 
        [[[ 69,  70,  71,  72],
          [ 85,  86,  87,  88],
          [101, 102, 103, 104],
          [117, 118, 119, 120]]],
 
 
        [[[ 73,  74,  75,  76],
          [ 89,  90,  91,  92],
          [105, 106, 107, 108],
          [121, 122, 123, 124]]],
 
 
        [[[ 77,  78,  79,  8

In [14]:
lul = getblocks(sixtenb[0][0], (2, 2), False)
lul.shape, lul.strides, lul


((2, 2, 2, 2, 1),
 (32, 8, 16, 4, 4),
 array([[[[[ 1],
           [ 2]],
 
          [[17],
           [18]]],
 
 
         [[[ 3],
           [ 4]],
 
          [[19],
           [20]]]],
 
 
 
        [[[[33],
           [34]],
 
          [[49],
           [50]]],
 
 
         [[[35],
           [36]],
 
          [[51],
           [52]]]]]))

In [10]:
for i in range(16):
    sixtenb[i][:] = getblocks(sixtenb[i][0], (2, 2))
sixtenb.shape,sixtenb.strides, sixtenb

ValueError: could not broadcast input array from shape (4,1,2,2) into shape (1,4,4)

In [32]:
hehe[0], hehe[100], hehe[6554]

IndexError: index 6554 is out of bounds for axis 0 with size 4096

In [33]:
ret = combineBlocks(hehe, (512, 512), (16, 4))
ret.shape, ret.strides, ret

((512, 512, 1),
 (2048, 4, 4),
 array([[[     1],
         [     2],
         [     3],
         ...,
         [   510],
         [   511],
         [   512]],
 
        [[   513],
         [   514],
         [   515],
         ...,
         [  1022],
         [  1023],
         [  1024]],
 
        [[  1025],
         [  1026],
         [  1027],
         ...,
         [  1534],
         [  1535],
         [  1536]],
 
        ...,
 
        [[260609],
         [260610],
         [260611],
         ...,
         [261118],
         [261119],
         [261120]],
 
        [[261121],
         [261122],
         [261123],
         ...,
         [261630],
         [261631],
         [261632]],
 
        [[261633],
         [261634],
         [261635],
         ...,
         [262142],
         [262143],
         [262144]]]))

In [34]:
(ret.reshape(-1) == image.reshape(-1)).all()


True

In [35]:
for i in range(512):
    for j in range(512):
        if ret[i][j][0] != image[i][j]:
            print(i, j, ret[i][j][0], image[i][j])
